language: ruby

addons:
  postgresql: 11

dist: bionic

env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true

cache:
  bundler: true
  directories:
    - node_modules
  yarn: true

install:
  - bundle install --jobs 3 --retry 3
  - nvm install 12
  - node -v
  - npm i -g yarn
  - yarn

bundler_args: --without development,production

before_install:
  - gem install bundler

before_script:
  - cp config/database.yml.travis config/database.yml
  - bundle exec rails db:create db:migrate RAILS_ENV=test

script:
  - bundle exec rails webpacker:compile
  - bundle exec rails test RAILS_ENV=test
